import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_layout/Header";
import FooterSection from "./_layout/footer/FooterSection";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],
  variable: '--poppins',
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: "Shak's Auto Detailing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.variable}`}>
        <Header />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
